name       : ibus-libzhuyin
version    : 1.10.0
release    : 4
source     :
    - http://downloads.sourceforge.net/libzhuyin/ibus-libzhuyin/ibus-libzhuyin-1.10.0.tar.gz : 7e63f32fa550532cfebc64165f86eb6b297d83a3493364db2ffe368e6b889b4a
license    : GPL-2.0
component  : desktop
summary    : New Zhuyin engine based on libzhuyin for IBus
description: |
    New Zhuyin engine based on libzhuyin for IBus
builddeps  :
    - pkgconfig(ibus-1.0)
    - pkgconfig(libpinyin)
    - pkgconfig(opencc)
    - pkgconfig(python3)
    - pkgconfig(sqlite3)
    - libtool-devel
    - gettext-devel
    - gnome-common
setup      : |
    %autogen --disable-static \
             --with-python=python3 \
             --enable-opencc
build      : |
    %make
install    : |
    %make_install
