name       : ibus-libzhuyin
version    : 1.7.10
release    : 2
source     :
    - https://github.com/epico/ibus-libzhuyin/archive/1.7.10.tar.gz : b9b0870d799fb3a858d232a7592cd5de26c7bb77c293e232b07205b07aeebf38
license    : GPL-2.0
component  : desktop
summary    : New Zhuyin engine based on libzhuyin for IBus
description: |
    New Zhuyin engine based on libzhuyin for IBus
builddeps  :
    - pkgconfig(ibus-1.0)
    - pkgconfig(libzhuyin)
    - pkgconfig(opencc)
    - gnome-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
